update rooms set exam_seats = 53 where name = 'V201';
update rooms set exam_seats = 36 where name = 'V206';
update rooms set exam_seats = 0 where name = 'Laugardalur';
update rooms set exam_seats = 40 where name = 'M101';
update rooms set exam_seats = 25 where name = 'M103';
update rooms set exam_seats = 25 where name = 'M104';
update rooms set exam_seats = 32 where name = 'M105';
update rooms set exam_seats = 20 where name = 'M107';
update rooms set exam_seats = 34 where name = 'M110';
update rooms set exam_seats = 16 where name = 'M111';
update rooms set exam_seats = 0 where name = 'M112';
update rooms set exam_seats = 0 where name = 'M113';
update rooms set exam_seats = 16 where name = 'M116';
update rooms set exam_seats = 0 where name = 'M117';
update rooms set exam_seats = 17 where name = 'M119';
update rooms set exam_seats = 24 where name = 'M122';
update rooms set exam_seats = 0 where name = 'M123';
update rooms set exam_seats = 28 where name = 'M208';
update rooms set exam_seats = 32 where name = 'M209';
update rooms set exam_seats = 0 where name = 'M210';
update rooms set exam_seats = 0 where name = 'M215';
update rooms set exam_seats = 0 where name = 'V216';
update rooms set exam_seats = 0 where name = 'M217';
update rooms set exam_seats = 0 where name = 'M220';
update rooms set exam_seats = 0 where name = 'M327';
update rooms set exam_seats = 0 where name = 'U201';
update rooms set exam_seats = 36 where name = 'V101';
update rooms set exam_seats = 31 where name = 'V102';
update rooms set exam_seats = 0 where name = 'V103';
update rooms set exam_seats = 0 where name = 'V104';
update rooms set exam_seats = 0 where name = 'V105';
update rooms set exam_seats = 0 where name = 'V106';
update rooms set exam_seats = 18 where name = 'V107';
update rooms set exam_seats = 18 where name = 'V108';
update rooms set exam_seats = 16 where name = 'V109';
update rooms set exam_seats = 11 where name = 'V110';
update rooms set exam_seats = 0 where name = 'V111';
update rooms set exam_seats = 0 where name = 'V112';
update rooms set exam_seats = 0 where name = 'V113 Efnafræðistofa';
update rooms set exam_seats = 0 where name = 'V118 Vélsmiðja';
update rooms set exam_seats = 36 where name = 'V206';
update rooms set exam_seats = 0 where name = 'V207 Rafeinda- og stýritæknistofa';
update rooms set exam_seats = 0 where name = 'V209 Eðlisfræðistofa';
update rooms set exam_seats = 0 where name = 'V220';
update rooms set exam_seats = 0 where name = 'Verður birt seinna';